# example workflow for Black Duck scans using the Detect Action
# https://github.com/marketplace/actions/detect-rapid-scan-action
name: bd-detect-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: synopsys-sig/detect-action@v0.3.4
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
        DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
      with:
        blackduck-url: ${{ vars.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        detect-version: 9.4.0
        scan-mode: INTELLIGENT
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Black Duck PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: synopsys-sig/detect-action@v0.3.4
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.base_ref }}
        DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.base_ref }}
      with:
        blackduck-url: ${{ vars.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        detect-version: 9.4.0
        scan-mode: RAPID
        github-token: ${{ secrets.GITHUB_TOKEN }}
