# example workflow for Coverity on Polaris
name: coverity-on-polaris-win64
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: windows-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      env:
        POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      run: |
        Invoke-WebRequest -Uri ${{ vars.POLARIS_SERVER_URL }}/api/tools/polaris_cli-win64.zip -OutFile polaris.zip
        Expand-Archive -Path polaris.zip -DestinationPath ${{ runner.temp }} -Force
        Remove-Item -Path polaris.zip -Force
        ${{ runner.temp }}/*/bin/polaris.exe --co project.name=chuckaude-${{ github.event.repository.name }} analyze -w
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: polaris-cli-logs
#        path: ${{ github.workspace }}/.synopsys
