# example workflow for SRM scans using the Bridge CLI
name: srm-bridge-cli
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  srm:
    runs-on: ubuntu-latest
    env:
      BRIDGE_SRM_URL: ${{ vars.SRM_URL }}
      BRIDGE_SRM_APIKEY: ${{ secrets.SRM_APIKEY }}
      BRIDGE_SRM_ASSESSMENT_TYPES: 'SAST,SCA'
      BRIDGE_SRM_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_SRM_BRANCH_NAME: ${{ github.event.ref_name }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: SRM Full Scan
      run: |
        curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d ${{ runner.temp }} bridge.zip && rm -f bridge.zip
        ${{ runner.temp }}/synopsys-bridge --stage srm
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
